In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
B = np.array([[3, 0], [0, 6]])
B

array([[3, 0],
       [0, 6]])

In [5]:
A * B

array([[ 3,  0],
       [ 0, 24]])

# パーセプトロンの実装

In [8]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

In [11]:
AND(0.5, 0.5)

0

In [12]:
x = np.array([0, 1])
w = np.array([0.5, 0.5])
b = -0.7

In [13]:
w*x

array([0. , 0.5])

In [15]:
np.sum(w*x) + b

-0.19999999999999996

In [16]:
def AND2(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tmp = np.sum(x*w) + b 
    if tmp <= 0:
        return 0
    elif tmp > 0:
        return 1

In [18]:
AND2(0.2,1)

0